language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "pypy"

before_install:
  pip install codecov

matrix:
#  allow_failures:
#    - python: "3.5"
#    - python: "3.6"
#    - python: "3.7"
  include:
    - python: 2.7
      install: pip install -U flake8
      script: flake8 --ignore E501,W191,C901,E265,E402,E117
      after_success:
    - python: 3.5
      install: pip install -U flake8
      script: flake8 --ignore E501,W191,C901,E265,E402,E117
      after_success:
#    - python: 2.7
#      install: pip install -U isort
#      script: isort -c --diff
#      after_success:

install:
  - pip install -Ur requirements-test.txt
  - pip install -Ue .

script: python setup.py test

after_success:
  - codecov
  - coveralls

notifications:
  irc: "chat.freenode.net#httoop"
