language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
  pip install codecov
install:
  - pip install six
  - pip install pytest
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py install
script: python setup.py test
after_success:
  - codecov
  - coveralls
