[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "httoop.version.__version__" }

[project]
name = "httoop"
dynamic = ["version"]
license = { text = "MIT" }
description = "object oriented HTTP protocol library"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  { name = "SpaceOne", email = "space@wechall.net" }
]
keywords = ["HTTP", "web", "proxy", "cache", "client", "server", "library"]
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Natural Language :: English",
  "Operating System :: POSIX :: BSD",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Server",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

requires-python = ">=3.9"

[project.optional-dependencies]
xml = ["defusedxml"]
hal = ["uritemplate"]

[dependency-groups]
test = [
  "pytest",
  "pytest-cov",
  "coveralls",
  "defusedxml",
]

[tool.pytest.ini_options]
addopts = "-s -l -vv --tb=native --strict-markers --cov=httoop --cov-report=xml --cov-report=term-missing"

[tool.setuptools]
zip-safe = true

[tool.setuptools.packages.find]
include = ["httoop*"]
exclude = ["debian.*", "tests.*", "rfc.*"]

[project.urls]
Homepage = "https://github.com/spaceone/httoop"

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
]

[tool.ty.terminal]
output-format = "concise"

[tool.ty.environment]
python-version = "3.8"

[tool.mypy]
python_version = "3.10"
strict = true
show_error_codes = true
explicit_package_bases = true
namespace_packages = true
mypy_path = ["httoop"]
files = ["httoop/"]

[tool.ruff]
line-length = 180
target-version = "py37"
output-format = "concise"
unsafe-fixes = true

[tool.ruff.lint]
preview = true
select = ["E", "W", "F", "I", "D", "TD", "ALL"]
ignore = [
# Invalid / don't care:
 "RUF105",  # noqa-comments
 "RUF106",  # rule-codes-in-suppression-comments:
 "RUF201",  # rule-codes-in-selectors
 "E501",  # line-too-long
 "E203",  # whitespace-before-punctuation
 "COM812",  # missing-trailing-comma
 "D203",  # one-blank-line-before-class
 "D212",  # multi-line-summary-first-line
 "D400",  # ends-in-period
 "D415",  # ends-in-punctuation
 "D100",  # Missing docstring in public module
 "D101",  # Missing docstring in public class
 "D102",  # Missing docstring in public method
 "D103",  # Missing docstring in public function
 "D105",  # Missing docstring in magic method
 "D107",  # Missing docstring in `__init__`
 "D205",  # 1 blank line required between summary line and description
 "D211",  # blank-line-before-class
 "D212",  # multi-line-summary-first-line
 "D401",  # First line of docstring should be in imperative mood: "A shortcut to abspath, escape and lowercase."
 "D402",  # First line should not be the function's signature
 "D403",  # first-word-uncapitalized
 "D404",  # First word of the docstring should not be "This"
 "D413",  # missing-blank-line-after-last-section
 "D104",  # Missing docstring in public package
 "DOC201",  # docstring-missing-returns
 "DOC402",  # docstring-missing-yields
 "DOC501",  # docstring-missing-exception
 "EM101", # raw-string-in-exception
 "ERA001", # commented-out-code
 "T201", "T203",  # print, p-print
 "TD001",  # invalid-todo-tag
 "TD002",  # missing-todo-author
 "TD003",  # missing-todo-link
 "RSE102",  # unnecessary-paren-on-raise-exception
 "UP031",  # printf-string-formatting
 "CPY",  # copyright
 "EM102",  # f-string-in-exception
 # "I", "S101", "Q000", "ANN", "ERA", "UP004", "ARG001", "ARG002",
 "FURB189",  # subclass-builtin
 "TRY301",  # raise-within-try

# too much effort:
 "ANN001",  # missing-type-function-argument
 "ANN201",  # missing-return-type-undocumented-public-function
 "ANN202",  # missing-return-type-private-function
 "ANN002",  # missing-type-args
 "ANN003",  # missing-type-kwargs
 "ANN401",  # any-type
 "ANN204",  # missing-return-type-special-method
 "ANN206",  # missing-return-type-class-method

 "ARG001",  # unused-function-argument
 "ARG003",  # unused-class-method-argument
 "FIX001",  # line-contains-fixme
 "FIX002",  # line-contains-todo
 "PLC2701",  # import-private-name
 "PLR0904",  # too-many-public-methods
 "PLR0912",  # too-many-branches

# needs decision:
 "PLC2801",  # unnecessary-dunder-call
 "TRY003",  # raise-vanilla-args
 "TRY300",  # try-consider-else
]


# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

task-tags = ["TODO", "FIXME"]

[tool.ruff.lint.extend-per-file-ignores]
"tests/*" = [
 "ANN",
 "S101",  # assert
 "S105",  # hardcoded-password-string
 "S108",  # hardcoded-temp-file
 "S404",  # suspicious-subprocess-import
 "S405",  # suspicious-xml-etree-import
 "S603",  # subprocess-without-shell-equals-true
]
"httoop/status/*.py" = [
 "N801",
]

[tool.ruff.lint.mccabe]
max-complexity = 40

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "csv"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
combine-as-imports = true
#filter-files = true
#force-grid-wrap = false
known-first-party = ["httoop"]
# https://github.com/astral-sh/ruff/issues/2600 :
#multi-line-output = 5
#include-trailing-comma = true
lines-after-imports = 2
split-on-trailing-comma = false

# length-sort = true
