[build-system]
requires = ["setuptools>=61", "six"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "httoop.version.__version__" }

[project]
name = "httoop"
# version = "0.1.1"
dynamic = ["version"]
description = "object oriented HTTP protocol library"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  { name = "SpaceOne", email = "space@wechall.net" }
]
license = { text = "MIT" }
keywords = ["HTTP", "web", "proxy", "cache", "client", "server", "library"]
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: POSIX :: BSD",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Server",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

requires-python = ">=3.8"

dependencies = ["six"]

[project.optional-dependencies]
xml = ["defusedxml"]
hal = ["uritemplate"]
test = [
  "pytest",
  "pytest-cov",
  "coveralls",
  "defusedxml",
]

[tool.pytest.ini_options]
addopts = "--tb=native --strict-markers --cov=httoop --cov-report=xml --cov-report=term-missing"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "tests.*"]

[tool.setuptools]
zip-safe = true

[project.urls]
Homepage = "https://github.com/spaceone/httoop"
